Spring: 
    datasource:
        url: jdbc:postgresql://localhost:5432/warehaus2
        username: postgres
        password: postgres1
    
    output:
        ansi:
            enabled: always

logging:
    level:
        com:
            skillsotmr: debug